[package]
name = "{{project-name}}"
authors = ["{{authors}}"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
version = "0.0.0"

[dependencies]
cortex-m = "0.7.1"
cortex-m-rt = "0.6.10"
cortex-m-rtic = "0.5.5"
panic-halt = "0.2.0"
stm32g0xx-hal = { version = "0.1.0", features = ["rt", "stm32g031"] }

[profile.dev]
incremental = false

[profile.release]
debug = false
codegen-units = 1
incremental = false
lto = true
