[target.thumbv6m-none-eabi]
# runner = "probe-run --chip STM32C011F6Px"
runner = "probe-rs-cli run --chip STM32C011F6Px"
# runner = "arm-none-eabi-gdb -q"

rustflags = [
  "-C", "linker=arm-none-eabi-ld",
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"